server:
  port: 9000
ui:
 url: http://localhost:8088

security:
  jwt:
    key-store: classpath:keystore.jks
    key-store-password: letmein
    key-pair-alias: mytestkey
    key-pair-password: changeme

spring:
#    datasource:
#        driver-class-name: com.mysql.jdbc.Driver
#        password: root
#        url: jdbc:mysql://localhost:3306/authserver
#        username: root
    jersey:
      application-path: /api
    JACKSON:
     serialization:
      INDENT_OUTPUT: true
      
    jpa:
       hibernate:
         ddl-auto: none
         naming:
           implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
           physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
       properties:
           hibernate:
               dialect: org.hibernate.dialect.MySQL5InnoDBDialect
       database-platform: org.hibernate.dialect.H2Dialect
    datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:authserver;DATABASE_TO_UPPER=false;
      username: sa
      password:
    data:
      jpa:
        repositories:
          bootstrap-mode: default
    h2:
      console:
        enabled: true
        path: /h2-console
jwt:
   header: Authorization
   secret: jwtbenaaSecretKey
   expiration: 604800
   route:
    authentication:
     path: auth
     refresh: refresh

#        jwt.header=Authorization
#        jwt.secret= jwtbenaaSecretKey
#        jwt.expiration=604800
#        jwt.route.authentication.path= auth
#        jwt.route.authentication.refresh= refresh
